let config = {
  preloaderDelay: 1,

  showDelay: 1.5,

  title: "storm",

  social: {
    telegram: "tokenzo",
    telegramchannel: "+fUfMcOO1WbpjMjk0",
  },

  preloaderColor: "#00e5ff",

  playButtonColor: "#00e5ff",
  playButtonShadowColor: "rgba(0, 229, 255, 0.3)",

  titleColor: "#ffffff",
  titleShadowColor: "#00e5ff",

  copyrightText: [
    "storm soon.",
    "storm is coming.",
    "prepare for the storm.",
    "storm incoming.",
    "the storm awakens.",
    "unleash the storm.",
    "caught in the storm.",
    "storm mode activated.",
    "riding the storm.",
    "calm before the storm.",
    "storm on the horizon.",
    "storm strikes hard.",
    "brace for impact. storm.",
    "storm level: maximum.",
    "welcome to the storm.",
    "storm never stops.",
    "storm in your veins.",
    "feel the storm.",
    "storm takes no prisoners.",
    "code the storm.",
    "storm writes the rules.",
    "you vs the storm.",
    "storm always wins.",
    "the storm has spoken.",
    "storm certified.",
    "born from the storm.",
    "the storm is here.",
    "storm reigns supreme.",
    "bow to the storm.",
    "storm mode: ON.",
    "unleashed the storm.",
    "storm logic prevails.",
    "caught in the eye of the storm.",
    "storm dominates.",
    "hail to the storm.",
    "the storm rises.",
    "storm in full force.",
    "you can't escape the storm.",
    "storm builds momentum.",
    "the storm decides.",
    "storm: final form.",
    "respect the storm.",
    "fear the storm.",
    "the storm never sleeps.",
    "storm is eternal.",
    "dance with the storm.",
    "the storm questions nothing.",
    "storm compiles faster.",
    "welcome to storm season.",
    "the storm era begins.",
    "storm evolution.",
    "channel the storm.",
    "storm powers everything.",
    "the ultimate storm.",
    "storm's chosen one.",
    "storm above all.",
    "the storm prevails.",
    "storm: ascended.",
    "taste the storm.",
    "the storm judges you.",
    "storm legacy.",
    "embrace the storm.",
    "the storm is calling.",
    "storm alpha released.",
    "bound by the storm.",
    "the storm prophecy.",
    "storm eternal glory.",
    "one with the storm.",
    "the storm path chosen.",
    "storm: no mercy.",
    "dive into the storm.",
    "the storm remembers.",
    "when the storm awakens.",
  ],
  copyrightTextColor: "#00e5ff",

  socialColor: "#aaaaaa",
  socialShadowColor: "rgba(0, 0, 0, 0)",
};
